// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQIgP_RPMywLoiEmLe5_UxJKLvnRZDnw',
    appId: '1:154392513274:web:62ebe1cb4b2c83382fd743',
    messagingSenderId: '154392513274',
    projectId: 'flutter-app-10157',
    authDomain: 'flutter-app-10157.firebaseapp.com',
    storageBucket: 'flutter-app-10157.firebasestorage.app',
    measurementId: 'G-PPDD3XYGR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBuoEyPDfs-HOCOgAwaz3cIkTybFLLU8',
    appId: '1:154392513274:android:4a4c60483d54ead22fd743',
    messagingSenderId: '154392513274',
    projectId: 'flutter-app-10157',
    storageBucket: 'flutter-app-10157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp-Hu3r_HXBByDIBpL48whsc-U_qXlVSk',
    appId: '1:154392513274:ios:ac738bcbfe615c9a2fd743',
    messagingSenderId: '154392513274',
    projectId: 'flutter-app-10157',
    storageBucket: 'flutter-app-10157.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp-Hu3r_HXBByDIBpL48whsc-U_qXlVSk',
    appId: '1:154392513274:ios:ac738bcbfe615c9a2fd743',
    messagingSenderId: '154392513274',
    projectId: 'flutter-app-10157',
    storageBucket: 'flutter-app-10157.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUQIgP_RPMywLoiEmLe5_UxJKLvnRZDnw',
    appId: '1:154392513274:web:913b84fc7de565842fd743',
    messagingSenderId: '154392513274',
    projectId: 'flutter-app-10157',
    authDomain: 'flutter-app-10157.firebaseapp.com',
    storageBucket: 'flutter-app-10157.firebasestorage.app',
    measurementId: 'G-0VZXL13BTR',
  );
}
